baseURL: https://iansmcb.com
languageCode: en-us
theme: smigle
title: Ian S. McBride
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 3
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 4
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 5
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 6
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 7
params:
  abbrDateFmt: Jan 2
  author: Ian S. McBride
  brandIconFile: images/avatar.jpg
  customStylesheets:
    - css/custom.css
  dateFmt: 2006-01-02
  social:
    - name: GitHub
      url: https://github.com/ian-s-mcb
    - name: GitLab
      url: https://gitlab.com/ian-s-mcb
    - name: Quizlet
      url: https://quizlet.com/ian-s-mcb
    - name: Reddit
      url: https://www.reddit.com/user/ian-s-mcb
    - name: StackOverflow
      url: https://stackoverflow.com/users/3417846/ian-s-mcb
  subtitle: Software Engineer
